---
- hosts: all
  gather_facts: false
  tasks:
    - name: install rails
      sudo: true
      dnf: pkg={{item}} state=latest
      with_items:
          - ruby
          - rubygem-rails
          - gcc
          - zlib-devel
          - sqlite-devel
          - ruby-devel
          - rubygems
          - nodejs

    - name: bundle install
      command: bundle install chdir=/vagrant/wine-application

    - name: seed db
      command: rake db:seed chdir=/vagrant/wine-application
