---
- hosts: all
  gather_facts: false
  tasks:
    - name: install packages for ansible support
      sudo: true
      raw: dnf -y -e0 -d0 install python python-dnf yum-utils python-pip

    - name: install rails
      sudo: true
      dnf: pkg={{item}} state=latest
      with_items:
          - ruby
          - rubygem-rails
          - gcc
          - zlib-devel
          - sqlite-devel
          - ruby-devel
          - rubygems
          - nodejs

    - name: bundle install
      command: bundle install chdir=/vagrant/wine-application

    - name: install supplier-api
      sudo: true
      command: pip install -e . chdir=/vagrant/service/

    - name: redirect port 80 to 8080
      sudo: true
      command: iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
